version: '3'

services:
  crawler:
    build:
      context: ./crawler
    depends_on:
      - postgres
    networks:
      - t0_net
    restart: on-failure:10

  postgres:
    build:
      context: ./postgres
    networks:
      - t0_net

  server:
    build:
      context: ./server
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: on-failure:10
    networks:
      - t0_net

networks:
  t0_net:
